swagger: '2.0'
info:
  description: This is the API documentation for the COP 4331 Marketplace App. Made by Jeovan Teixeira and Remi Roper.
  version: 1.0.0
  title: Marketplace App
  contact:
    email: je127364@ucf.edu

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /login:
    post:
      tags:
      - Users
      summary: Logs in to the marketplace app
      operationId: dlLogin
      description: Logs in to the marketplace app, returns empty info with an error string saying if it worked or not
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: loginUser
        description: Login
        schema:
          $ref: '#/definitions/Login'
      responses:
        "Empty Error String":
          description: OK
        "No Records Found":
          description: Login couldn't find the user in the Users table with their login and password
  /register:
    post:
      tags:
      - Users
      summary: Regisers new users in to the marketplace app
      operationId: dlRegister
      description: registers in to the marketplace app, returns empty info with an error string saying if it worked or not
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: registerUser
        description: Register
        schema:
          $ref: '#/definitions/Register'
      responses:
        "Empty Error String":
          description: OK
        "User Already Exists":
          description: Duplicate User has been Found
          
definitions:
  Login:
    type: object
    required:
    - Login
    - Password
    properties:
      username:
        type: string
        example: fred
      password:
        type: string
        example: secret
  Register:
    type: object
    required:
    - First Name
    - Last Name
    - Username
    - Password
    - Email
    - Phone Number
    properties:
      firstname:
        type: string
        example: Fred
      lastname:
        type: string
        example: Doe
      username:
        type: string
        example: fred111
      password:
        type: string
        example: secret
      email:
        type: string
        example: fred@fred.com
      phoneNumber:
        type: string
        example: 4079981234

host: cop4331-marketplace-98e1376d9db6.herokuapp.com
basePath: /api
schemes:
- https